language: go
go:
  - '1.10'
  - '1.11'
  - '1.12'
  - '1.13'
  - '1.14'
  - '1.15'

sudo: false

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get
  - go build

script:
  - make test
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore=vendor/

matrix:
  allow_failures:
    - go: '1.10'
